CREATE TABLE IF NOT EXISTS textbausteine (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bildungsbereich TEXT NOT NULL,
    text TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    aktiv INTEGER DEFAULT 1,
    erstellt_am DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_textbausteine_bereich ON textbausteine(bildungsbereich, aktiv, sort_order);

-- Standard-Bausteine (mit {name} Platzhalter)
INSERT OR IGNORE INTO textbausteine (bildungsbereich, text, sort_order) VALUES
('sprache',  '{name} zeigt großes Interesse an Büchern und lässt sich gerne vorlesen.', 1),
('sprache',  '{name} hat einen altersgemäßen Wortschatz und setzt ihn aktiv ein.', 2),
('sprache',  '{name} kommuniziert klar und verständlich mit Erwachsenen und anderen Kindern.', 3),
('sprache',  '{name} singt gerne Lieder mit und spricht Reime nach.', 4),
('sprache',  '{name} stellt viele Fragen und ist neugierig auf neue Wörter.', 5),
('sprache',  '{name} erzählt Erlebtes in zusammenhängenden Sätzen.', 6),
('motorik',  '{name} bewegt sich sicher und koordiniert in der Gruppe.', 1),
('motorik',  '{name} zeigt Freude an Bewegungsspielen und körperlicher Aktivität.', 2),
('motorik',  '{name} hält Stift und Schere altersgerecht und malt mit Ausdauer.', 3),
('motorik',  '{name} klettert, rennt und springt mit wachsender Sicherheit.', 4),
('motorik',  '{name} hat die Feinmotorik gut entwickelt und arbeitet konzentriert.', 5),
('motorik',  '{name} zieht sich selbstständig an und aus.', 6),
('sozial',   '{name} geht freundlich und einfühlsam mit anderen Kindern um.', 1),
('sozial',   '{name} beteiligt sich aktiv an Gruppenaktivitäten.', 2),
('sozial',   '{name} kann Konflikte zunehmend selbstständig lösen.', 3),
('sozial',   '{name} zeigt Mitgefühl und tröstet andere Kinder bei Bedarf.', 4),
('sozial',   '{name} hält sich an vereinbarte Regeln und Grenzen.', 5),
('sozial',   '{name} hat enge Freundschaften in der Gruppe entwickelt.', 6),
('kognitiv', '{name} zeigt ausgeprägte Neugier und Freude am Entdecken.', 1),
('kognitiv', '{name} löst Rätsel und Denkaufgaben mit Ausdauer und Fantasie.', 2),
('kognitiv', '{name} erkennt Zusammenhänge und zieht logische Schlüsse.', 3),
('kognitiv', '{name} konzentriert sich gut und arbeitet Aufgaben zu Ende.', 4),
('kognitiv', '{name} zeigt ein gutes Gedächtnis für Erlebtes und Gelerntes.', 5),
('kognitiv', '{name} zählt sicher und erkennt erste Mengen und Formen.', 6),
('kreativ',  '{name} malt und bastelt mit großer Begeisterung und Ausdauer.', 1),
('kreativ',  '{name} bringt eigene Ideen in Rollenspiele und Bauprojekte ein.', 2),
('kreativ',  '{name} experimentiert kreativ mit verschiedenen Materialien.', 3),
('kreativ',  '{name} gestaltet Werke mit erkennbaren Motiven und eigenem Stil.', 4),
('kreativ',  '{name} liebt es, Geschichten zu erfinden und nachzuspielen.', 5),
('kreativ',  '{name} zeigt Freude am freien Spiel und der eigenen Gestaltung.', 6),
('musik',    '{name} singt bekannte Lieder auswendig und mit Freude.', 1),
('musik',    '{name} hält den Rhythmus bei Musikspielen sicher mit.', 2),
('musik',    '{name} reagiert sensibel auf verschiedene Musikstile.', 3),
('musik',    '{name} spielt einfache Instrumente mit Begeisterung.', 4),
('musik',    '{name} tanzt ausdrucksstark und rhythmisch zur Musik.', 5),
('musik',    '{name} erkennt bekannte Melodien schnell wieder.', 6),
('natur',    '{name} beobachtet Pflanzen und Tiere mit großem Interesse.', 1),
('natur',    '{name} beteiligt sich begeistert am Gießen und Pflegen der Pflanzen.', 2),
('natur',    '{name} stellt viele Fragen zu Naturphänomenen.', 3),
('natur',    '{name} geht achtsam mit lebenden Wesen und der Natur um.', 4),
('natur',    '{name} kennt Jahreszeiten und typische Merkmale.', 5),
('natur',    '{name} freut sich über Ausflüge und Aktivitäten im Freien.', 6),
('alltag',   '{name} ist beim Tischdecken und Aufräumen zuverlässig dabei.', 1),
('alltag',   '{name} wäscht selbstständig die Hände und achtet auf Hygiene.', 2),
('alltag',   '{name} hält den eigenen Bereich ordentlich und räumt auf.', 3),
('alltag',   '{name} beteiligt sich aktiv am gemeinsamen Frühstück und Mittagessen.', 4),
('alltag',   '{name} schläft gut ein und erholt sich in der Ruhezeit.', 5),
('alltag',   '{name} kommt täglich fröhlich und motiviert zur Betreuung.', 6);
