CREATE TABLE IF NOT EXISTS unfaelle (
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,
    kind_id                 INTEGER NOT NULL REFERENCES kinder(id) ON DELETE CASCADE,
    datum                   DATE NOT NULL,
    uhrzeit                 TEXT DEFAULT '',
    ort                     TEXT DEFAULT '',
    gemeldet_am             TEXT DEFAULT '',
    einzelheiten            TEXT DEFAULT '',
    verletzungen            TEXT DEFAULT '',
    massnahmen              TEXT DEFAULT '[]',
    massnahmen_sonstige     TEXT DEFAULT '',
    praevention             TEXT DEFAULT '',
    zeuge1_name             TEXT DEFAULT '',
    zeuge1_kontakt          TEXT DEFAULT '',
    zeuge2_name             TEXT DEFAULT '',
    zeuge2_kontakt          TEXT DEFAULT '',
    zeuge3_name             TEXT DEFAULT '',
    zeuge3_kontakt          TEXT DEFAULT '',
    ausgefuellt_von         TEXT DEFAULT '',
    ausgefuellt_datum       TEXT DEFAULT '',
    genehmigt_von           TEXT DEFAULT '',
    genehmigt_datum         TEXT DEFAULT '',
    unterschrift_stempel    TEXT DEFAULT '',
    unfallkasse_gemeldet    INTEGER DEFAULT 0,
    status                  TEXT DEFAULT 'entwurf',
    erstellt_am             DATETIME DEFAULT CURRENT_TIMESTAMP
);
